USE MASTER

CREATE DATABASE NoteBaseTest
/* DROP DATABASE NoteBase */
GO
USE  NoteBase

/*creating tables */
CREATE TABLE Tag (
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Title VARCHAR(50) NOT NULL
);

CREATE TABLE Person (
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL
);

CREATE TABLE Category (
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Title VARCHAR(50) NOT NULL,
	PersonId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Person(ID)
	UNIQUE(Title, PersonId)
);

CREATE TABLE Note (
	ID UNIQUEIDENTIFIER DEFAULT NEWID() PRIMARY KEY,
	Title VARCHAR(50),
	Text VARCHAR(1000) NOT NULL,
	CategoryID UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Category(ID),
	PersonId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Person(ID)
);

CREATE TABLE NoteTag (
	NoteID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Note(ID),
	TagID UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Tag(ID),
	PRIMARY KEY(NoteID, TagID)
);