USE MASTER

CREATE DATABASE NoteBase
/* DROP DATABASE NoteBase */
GO
USE  NoteBase

/*creating tables */
CREATE TABLE Tag (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Title VARCHAR(50) NOT NULL
);

CREATE TABLE Category (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Title VARCHAR(50) NOT NULL
);

CREATE TABLE [User] (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	[Name] VARCHAR(50) NOT NULL,
	Email VARCHAR(50) NOT NULL,
	EncryptedPassword VARCHAR(500) NOT NULL
);

CREATE TABLE Note (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Title VARCHAR(50),
	MainBody VARCHAR(1000) NOT NULL,
	CategoryID INT NOT NULL FOREIGN KEY REFERENCES Category(ID),
	UserID INT NOT NULL FOREIGN KEY REFERENCES [User](ID)
);

CREATE TABLE NoteTag (
	NoteID INT NOT NULL FOREIGN KEY REFERENCES Note(ID),
	TagID INT NOT NULL FOREIGN KEY REFERENCES Tag(ID),
	PRIMARY KEY(NoteID, TagID)
);