USE MASTER

CREATE DATABASE NoteBase
/* DROP DATABASE NoteBase */
GO
USE  NoteBase

/*creating tables */
CREATE TABLE Tag (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Title VARCHAR(50) NOT NULL
);

CREATE TABLE Person (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Name VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL
);

CREATE TABLE Category (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Title VARCHAR(50) NOT NULL,
	PersonId INT NOT NULL FOREIGN KEY REFERENCES Person(ID)
	UNIQUE(Title, PersonId)
);

CREATE TABLE Note (
	ID INT IDENTITY(1, 1) PRIMARY KEY,
	Title VARCHAR(50),
	Text VARCHAR(1000) NOT NULL,
	CategoryID INT FOREIGN KEY REFERENCES Category(ID),
	PersonId INT NOT NULL FOREIGN KEY REFERENCES Person(ID)
);

CREATE TABLE NoteTag (
	NoteID INT NOT NULL FOREIGN KEY REFERENCES Note(ID),
	TagID INT NOT NULL FOREIGN KEY REFERENCES Tag(ID),
	PRIMARY KEY(NoteID, TagID)
);